language: node_js
node_js:
  - 10
after_success:
  - mkdir src
  - cp -R src
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: src
  on:
    branch: master
